import { 
  Product, 
  Category, 
  Warehouse, 
  Location, 
  StockBalance, 
  Receipt, 
  Delivery, 
  Transfer, 
  Adjustment, 
  StockLedgerEntry, 
  CompanySettings,
  UserProfile,
  ReorderingRule 
} from '../types';

export const SEED_USERS: UserProfile[] = [
  {
    id: 'user_admin_01',
    name: 'Alexandra Vance',
    email: 'admin@stocksense.com',
    role: 'Admin',
    phone: '+1 (555) 019-2834',
    active: true,
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'user_mgr_01',
    name: 'Marcus Sterling',
    email: 'manager@stocksense.com',
    role: 'Inventory Manager',
    phone: '+1 (555) 024-9182',
    active: true,
    createdAt: '2025-01-11T09:30:00Z',
    updatedAt: '2025-01-11T09:30:00Z',
  },
  {
    id: 'user_staff_01',
    name: 'Devon Miller',
    email: 'staff@stocksense.com',
    role: 'Warehouse Staff',
    phone: '+1 (555) 038-7711',
    active: true,
    createdAt: '2025-01-12T10:15:00Z',
    updatedAt: '2025-01-12T10:15:00Z',
  },
];

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_raw_materials',
    name: 'Raw Materials',
    description: 'Bulk industrial metals, bars, and fabrication stock',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat_furniture',
    name: 'Office Furniture',
    description: 'Chairs, desks, workstations, and ergonomic equipment',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat_electronics',
    name: 'IT & Electronics',
    description: 'Computing hardware, screens, input peripherals, and devices',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat_packaging',
    name: 'Packaging & Supplies',
    description: 'Boxes, protective cartons, tape, and shipping materials',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cat_safety',
    name: 'Safety & PPE',
    description: 'Industrial helmets, vests, safety gear, and protection',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
];

export const SEED_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh_main',
    name: 'Main Warehouse',
    code: 'WH-MAIN',
    address: '450 Logistics Parkway, Industrial Zone A, Chicago, IL',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'wh_prod',
    name: 'Production Warehouse',
    code: 'WH-PROD',
    address: '88 Assembly Drive, Manufacturing Plant 2, Detroit, MI',
    active: true,
    createdAt: '2025-01-01T00:00:00Z',
  },
];

export const SEED_LOCATIONS: Location[] = [
  {
    id: 'loc_rack_a',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    name: 'Rack A - Heavy Stock',
    code: 'MAIN/RACK-A',
    active: true,
  },
  {
    id: 'loc_rack_b',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    name: 'Rack B - Finished Units',
    code: 'MAIN/RACK-B',
    active: true,
  },
  {
    id: 'loc_rack_c',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    name: 'Rack C - Small Components',
    code: 'MAIN/RACK-C',
    active: true,
  },
  {
    id: 'loc_prod_floor',
    warehouseId: 'wh_prod',
    warehouseName: 'Production Warehouse',
    name: 'Production Floor',
    code: 'PROD/FLOOR',
    active: true,
  },
  {
    id: 'loc_finished_goods',
    warehouseId: 'wh_prod',
    warehouseName: 'Production Warehouse',
    name: 'Finished Goods Bay',
    code: 'PROD/FIN-GOODS',
    active: true,
  },
  {
    id: 'loc_bulk_storage',
    warehouseId: 'wh_prod',
    warehouseName: 'Production Warehouse',
    name: 'Bulk Raw Storage',
    code: 'PROD/BULK',
    active: true,
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_steel_rod',
    name: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    categoryId: 'cat_raw_materials',
    categoryName: 'Raw Materials',
    unitOfMeasure: 'kg',
    description: 'High tensile carbon steel reinforcing rod for structural framing',
    reorderLevel: 50,
    totalStock: 140,
    reservedStock: 20,
    availableStock: 120,
    price: 45.00,
    cost: 28.50,
    active: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-20T14:30:00Z',
  },
  {
    id: 'prod_office_chair',
    name: 'Ergonomic Office Chair',
    sku: 'FURN-CHR-002',
    categoryId: 'cat_furniture',
    categoryName: 'Office Furniture',
    unitOfMeasure: 'Units',
    description: 'Mesh executive task chair with adjustable lumbar and 3D armrests',
    reorderLevel: 15,
    totalStock: 35,
    reservedStock: 5,
    availableStock: 30,
    price: 189.99,
    cost: 110.00,
    active: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-21T10:00:00Z',
  },
  {
    id: 'prod_laptop',
    name: 'Pro Laptop 15" i7 32GB',
    sku: 'ELEC-LPT-003',
    categoryId: 'cat_electronics',
    categoryName: 'IT & Electronics',
    unitOfMeasure: 'Units',
    description: 'Enterprise developer workstation laptop with 1TB NVMe SSD',
    reorderLevel: 10,
    totalStock: 8, // Low Stock!
    reservedStock: 2,
    availableStock: 6,
    price: 1299.00,
    cost: 950.00,
    active: true,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-22T16:00:00Z',
  },
  {
    id: 'prod_printer',
    name: 'Industrial Label Printer',
    sku: 'ELEC-PRN-004',
    categoryId: 'cat_electronics',
    categoryName: 'IT & Electronics',
    unitOfMeasure: 'Units',
    description: 'Thermal transfer high-speed barcode and packaging label printer',
    reorderLevel: 5,
    totalStock: 3, // Low Stock!
    reservedStock: 1,
    availableStock: 2,
    price: 499.00,
    cost: 320.00,
    active: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-22T17:15:00Z',
  },
  {
    id: 'prod_box',
    name: 'Heavy Duty Packing Box 40x40',
    sku: 'PKG-BOX-005',
    categoryId: 'cat_packaging',
    categoryName: 'Packaging & Supplies',
    unitOfMeasure: 'Units',
    description: 'Double-walled corrugated shipping cardboard box',
    reorderLevel: 100,
    totalStock: 450,
    reservedStock: 50,
    availableStock: 400,
    price: 3.50,
    cost: 1.20,
    active: true,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-23T09:00:00Z',
  },
  {
    id: 'prod_keyboard',
    name: 'Wireless Mechanical Keyboard',
    sku: 'ELEC-KBD-006',
    categoryId: 'cat_electronics',
    categoryName: 'IT & Electronics',
    unitOfMeasure: 'Units',
    description: 'Tenkeyless tactile switch bluetooth/2.4G wireless keyboard',
    reorderLevel: 25,
    totalStock: 65,
    reservedStock: 10,
    availableStock: 55,
    price: 85.00,
    cost: 48.00,
    active: true,
    createdAt: '2025-01-07T00:00:00Z',
    updatedAt: '2025-01-23T11:45:00Z',
  },
  {
    id: 'prod_mouse',
    name: 'Precision Optical Mouse',
    sku: 'ELEC-MUS-007',
    categoryId: 'cat_electronics',
    categoryName: 'IT & Electronics',
    unitOfMeasure: 'Units',
    description: 'Rechargeable wireless ergonomic mouse with hyper-fast scroll',
    reorderLevel: 30,
    totalStock: 25, // Low Stock!
    reservedStock: 5,
    availableStock: 20,
    price: 49.00,
    cost: 26.00,
    active: true,
    createdAt: '2025-01-07T00:00:00Z',
    updatedAt: '2025-01-24T12:00:00Z',
  },
  {
    id: 'prod_monitor',
    name: '4K UltraHD 27" Monitor',
    sku: 'ELEC-MON-008',
    categoryId: 'cat_electronics',
    categoryName: 'IT & Electronics',
    unitOfMeasure: 'Units',
    description: 'IPS USB-C 65W Power Delivery professional color-accurate display',
    reorderLevel: 12,
    totalStock: 0, // Out of Stock!
    reservedStock: 0,
    availableStock: 0,
    price: 349.00,
    cost: 240.00,
    active: true,
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-24T14:10:00Z',
  },
  {
    id: 'prod_desk',
    name: 'Motorized Standing Desk 60x30',
    sku: 'FURN-DSK-009',
    categoryId: 'cat_furniture',
    categoryName: 'Office Furniture',
    unitOfMeasure: 'Units',
    description: 'Dual-motor height adjustable sit-stand desk with anti-collision',
    reorderLevel: 10,
    totalStock: 18,
    reservedStock: 4,
    availableStock: 14,
    price: 399.00,
    cost: 260.00,
    active: true,
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-24T15:25:00Z',
  },
  {
    id: 'prod_helmet',
    name: 'Hard Hat Safety Helmet',
    sku: 'SAF-HLM-010',
    categoryId: 'cat_safety',
    categoryName: 'Safety & PPE',
    unitOfMeasure: 'Units',
    description: 'ANSI Z89.1 Type 1 Class E certified ventilated construction helmet',
    reorderLevel: 40,
    totalStock: 95,
    reservedStock: 15,
    availableStock: 80,
    price: 24.50,
    cost: 11.80,
    active: true,
    createdAt: '2025-01-09T00:00:00Z',
    updatedAt: '2025-01-25T09:10:00Z',
  },
];

export const SEED_STOCK_BALANCES: StockBalance[] = [
  { id: 'prod_steel_rod_loc_rack_a', productId: 'prod_steel_rod', warehouseId: 'wh_main', locationId: 'loc_rack_a', quantity: 90, updatedAt: '2025-01-20T14:30:00Z' },
  { id: 'prod_steel_rod_loc_bulk_storage', productId: 'prod_steel_rod', warehouseId: 'wh_prod', locationId: 'loc_bulk_storage', quantity: 50, updatedAt: '2025-01-20T14:30:00Z' },

  { id: 'prod_office_chair_loc_rack_b', productId: 'prod_office_chair', warehouseId: 'wh_main', locationId: 'loc_rack_b', quantity: 20, updatedAt: '2025-01-21T10:00:00Z' },
  { id: 'prod_office_chair_loc_finished_goods', productId: 'prod_office_chair', warehouseId: 'wh_prod', locationId: 'loc_finished_goods', quantity: 15, updatedAt: '2025-01-21T10:00:00Z' },

  { id: 'prod_laptop_loc_rack_c', productId: 'prod_laptop', warehouseId: 'wh_main', locationId: 'loc_rack_c', quantity: 8, updatedAt: '2025-01-22T16:00:00Z' },

  { id: 'prod_printer_loc_rack_c', productId: 'prod_printer', warehouseId: 'wh_main', locationId: 'loc_rack_c', quantity: 3, updatedAt: '2025-01-22T17:15:00Z' },

  { id: 'prod_box_loc_rack_a', productId: 'prod_box', warehouseId: 'wh_main', locationId: 'loc_rack_a', quantity: 250, updatedAt: '2025-01-23T09:00:00Z' },
  { id: 'prod_box_loc_bulk_storage', productId: 'prod_box', warehouseId: 'wh_prod', locationId: 'loc_bulk_storage', quantity: 200, updatedAt: '2025-01-23T09:00:00Z' },

  { id: 'prod_keyboard_loc_rack_c', productId: 'prod_keyboard', warehouseId: 'wh_main', locationId: 'loc_rack_c', quantity: 45, updatedAt: '2025-01-23T11:45:00Z' },
  { id: 'prod_keyboard_loc_finished_goods', productId: 'prod_keyboard', warehouseId: 'wh_prod', locationId: 'loc_finished_goods', quantity: 20, updatedAt: '2025-01-23T11:45:00Z' },

  { id: 'prod_mouse_loc_rack_c', productId: 'prod_mouse', warehouseId: 'wh_main', locationId: 'loc_rack_c', quantity: 25, updatedAt: '2025-01-24T12:00:00Z' },

  { id: 'prod_monitor_loc_rack_b', productId: 'prod_monitor', warehouseId: 'wh_main', locationId: 'loc_rack_b', quantity: 0, updatedAt: '2025-01-24T14:10:00Z' },

  { id: 'prod_desk_loc_rack_a', productId: 'prod_desk', warehouseId: 'wh_main', locationId: 'loc_rack_a', quantity: 10, updatedAt: '2025-01-24T15:25:00Z' },
  { id: 'prod_desk_loc_finished_goods', productId: 'prod_desk', warehouseId: 'wh_prod', locationId: 'loc_finished_goods', quantity: 8, updatedAt: '2025-01-24T15:25:00Z' },

  { id: 'prod_helmet_loc_rack_b', productId: 'prod_helmet', warehouseId: 'wh_main', locationId: 'loc_rack_b', quantity: 60, updatedAt: '2025-01-25T09:10:00Z' },
  { id: 'prod_helmet_loc_prod_floor', productId: 'prod_helmet', warehouseId: 'wh_prod', locationId: 'loc_prod_floor', quantity: 35, updatedAt: '2025-01-25T09:10:00Z' },
];

export const SEED_RECEIPTS: Receipt[] = [
  {
    id: 'rec_001',
    receiptNumber: 'REC-2026-0001',
    supplier: 'Apex Steel Industries Inc.',
    date: '2026-01-15T09:00:00Z',
    destinationWarehouseId: 'wh_main',
    destinationWarehouseName: 'Main Warehouse',
    destinationLocationId: 'loc_rack_a',
    destinationLocationName: 'Rack A - Heavy Stock',
    notes: 'Q1 raw metal shipment arrived via flatbed container.',
    status: 'Done',
    items: [
      {
        productId: 'prod_steel_rod',
        productName: 'Steel Rod (10mm x 3m)',
        sku: 'RAW-STL-001',
        quantity: 50,
        unitOfMeasure: 'kg',
      }
    ],
    createdBy: 'user_mgr_01',
    createdByName: 'Marcus Sterling',
    createdAt: '2026-01-14T11:00:00Z',
    validatedAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 'rec_002',
    receiptNumber: 'REC-2026-0002',
    supplier: 'ErgoTech Office Wholesale',
    date: '2026-01-18T14:00:00Z',
    destinationWarehouseId: 'wh_main',
    destinationWarehouseName: 'Main Warehouse',
    destinationLocationId: 'loc_rack_b',
    destinationLocationName: 'Rack B - Finished Units',
    notes: 'Palletized chairs with assembly kits included.',
    status: 'Done',
    items: [
      {
        productId: 'prod_office_chair',
        productName: 'Ergonomic Office Chair',
        sku: 'FURN-CHR-002',
        quantity: 15,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_staff_01',
    createdByName: 'Devon Miller',
    createdAt: '2026-01-17T15:20:00Z',
    validatedAt: '2026-01-18T14:30:00Z',
  },
  {
    id: 'rec_003',
    receiptNumber: 'REC-2026-0003',
    supplier: 'TechSource Micro Distributing',
    date: '2026-01-26T10:00:00Z',
    destinationWarehouseId: 'wh_main',
    destinationWarehouseName: 'Main Warehouse',
    destinationLocationId: 'loc_rack_c',
    destinationLocationName: 'Rack C - Small Components',
    notes: 'Urgent restocking order for monitors and laptops.',
    status: 'Ready',
    items: [
      {
        productId: 'prod_monitor',
        productName: '4K UltraHD 27" Monitor',
        sku: 'ELEC-MON-008',
        quantity: 25,
        unitOfMeasure: 'Units',
      },
      {
        productId: 'prod_laptop',
        productName: 'Pro Laptop 15" i7 32GB',
        sku: 'ELEC-LPT-003',
        quantity: 10,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_mgr_01',
    createdByName: 'Marcus Sterling',
    createdAt: '2026-01-25T16:00:00Z',
  },
  {
    id: 'rec_004',
    receiptNumber: 'REC-2026-0004',
    supplier: 'Global Safety Gear Ltd.',
    date: '2025-01-27T11:00:00Z',
    destinationWarehouseId: 'wh_prod',
    destinationWarehouseName: 'Production Warehouse',
    destinationLocationId: 'loc_prod_floor',
    destinationLocationName: 'Production Floor',
    notes: 'Annual worker safety replenishment.',
    status: 'Draft',
    items: [
      {
        productId: 'prod_helmet',
        productName: 'Hard Hat Safety Helmet',
        sku: 'SAF-HLM-010',
        quantity: 50,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_staff_01',
    createdByName: 'Devon Miller',
    createdAt: '2025-01-26T08:30:00Z',
  }
];

export const SEED_DELIVERIES: Delivery[] = [
  {
    id: 'del_001',
    deliveryNumber: 'DEL-2026-0001',
    customer: 'Apex Innovations Corp',
    date: '2026-01-16T13:00:00Z',
    sourceWarehouseId: 'wh_main',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'loc_rack_b',
    sourceLocationName: 'Rack B - Finished Units',
    notes: 'Outfitted new headquarters branch floor.',
    status: 'Done',
    items: [
      {
        productId: 'prod_office_chair',
        productName: 'Ergonomic Office Chair',
        sku: 'FURN-CHR-002',
        quantity: 10,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_mgr_01',
    createdByName: 'Marcus Sterling',
    createdAt: '2026-01-15T10:00:00Z',
    validatedAt: '2026-01-16T13:45:00Z',
  },
  {
    id: 'del_002',
    deliveryNumber: 'DEL-2026-0002',
    customer: 'CyberSpace Labs',
    date: '2026-01-26T15:00:00Z',
    sourceWarehouseId: 'wh_main',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'loc_rack_c',
    sourceLocationName: 'Rack C - Small Components',
    notes: 'Awaiting courier pickup for peripherals.',
    status: 'Ready',
    items: [
      {
        productId: 'prod_keyboard',
        productName: 'Wireless Mechanical Keyboard',
        sku: 'ELEC-KBD-006',
        quantity: 5,
        unitOfMeasure: 'Units',
      },
      {
        productId: 'prod_mouse',
        productName: 'Precision Optical Mouse',
        sku: 'ELEC-MUS-007',
        quantity: 5,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_staff_01',
    createdByName: 'Devon Miller',
    createdAt: '2026-01-25T14:15:00Z',
  },
  {
    id: 'del_003',
    deliveryNumber: 'DEL-2026-0003',
    customer: 'Delta Engineering',
    date: '2026-01-28T09:30:00Z',
    sourceWarehouseId: 'wh_main',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'loc_rack_a',
    sourceLocationName: 'Rack A - Heavy Stock',
    notes: 'Structural steel bars for project site delivery.',
    status: 'Draft',
    items: [
      {
        productId: 'prod_steel_rod',
        productName: 'Steel Rod (10mm x 3m)',
        sku: 'RAW-STL-001',
        quantity: 20,
        unitOfMeasure: 'kg',
      }
    ],
    createdBy: 'user_mgr_01',
    createdByName: 'Marcus Sterling',
    createdAt: '2026-01-26T07:45:00Z',
  }
];

export const SEED_TRANSFERS: Transfer[] = [
  {
    id: 'trf_001',
    transferNumber: 'TRF-2026-0001',
    date: '2026-01-19T11:00:00Z',
    sourceWarehouseId: 'wh_main',
    sourceWarehouseName: 'Main Warehouse',
    sourceLocationId: 'loc_rack_a',
    sourceLocationName: 'Rack A - Heavy Stock',
    destinationWarehouseId: 'wh_prod',
    destinationWarehouseName: 'Production Warehouse',
    destinationLocationId: 'loc_bulk_storage',
    destinationLocationName: 'Bulk Raw Storage',
    notes: 'Transferred raw steel rod lot for subassembly pipeline.',
    status: 'Done',
    items: [
      {
        productId: 'prod_steel_rod',
        productName: 'Steel Rod (10mm x 3m)',
        sku: 'RAW-STL-001',
        quantity: 50,
        unitOfMeasure: 'kg',
      }
    ],
    createdBy: 'user_staff_01',
    createdByName: 'Devon Miller',
    createdAt: '2026-01-19T08:30:00Z',
    validatedAt: '2026-01-19T11:30:00Z',
  },
  {
    id: 'trf_002',
    transferNumber: 'TRF-2026-0002',
    date: '2026-01-26T16:00:00Z',
    sourceWarehouseId: 'wh_prod',
    sourceWarehouseName: 'Production Warehouse',
    sourceLocationId: 'loc_finished_goods',
    sourceLocationName: 'Finished Goods Bay',
    destinationWarehouseId: 'wh_main',
    destinationWarehouseName: 'Main Warehouse',
    destinationLocationId: 'loc_rack_b',
    destinationLocationName: 'Rack B - Finished Units',
    notes: 'Transfer completed desks to main distribution center.',
    status: 'Ready',
    items: [
      {
        productId: 'prod_desk',
        productName: 'Motorized Standing Desk 60x30',
        sku: 'FURN-DSK-009',
        quantity: 5,
        unitOfMeasure: 'Units',
      }
    ],
    createdBy: 'user_mgr_01',
    createdByName: 'Marcus Sterling',
    createdAt: '2026-01-25T13:00:00Z',
  }
];

export const SEED_ADJUSTMENTS: Adjustment[] = [
  {
    id: 'adj_001',
    adjustmentNumber: 'ADJ-2026-0001',
    date: '2026-01-20T16:00:00Z',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    locationId: 'loc_rack_a',
    locationName: 'Rack A - Heavy Stock',
    productId: 'prod_steel_rod',
    productName: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    unitOfMeasure: 'kg',
    systemQuantity: 93,
    physicalQuantity: 90,
    difference: -3,
    reason: 'Damaged materials during forklift offloading',
    notes: '3 kg bent beyond structural tolerance; scrapped according to QC rule.',
    status: 'Done',
    createdBy: 'user_staff_01',
    createdByName: 'Devon Miller',
    createdAt: '2026-01-20T15:45:00Z',
    validatedAt: '2026-01-20T16:00:00Z',
  }
];

export const SEED_LEDGER: StockLedgerEntry[] = [
  {
    id: 'ledg_001',
    productId: 'prod_steel_rod',
    productName: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    operationType: 'RECEIPT',
    referenceId: 'rec_001',
    referenceNumber: 'REC-2026-0001',
    toWarehouseId: 'wh_main',
    toWarehouseName: 'Main Warehouse',
    toLocationId: 'loc_rack_a',
    toLocationName: 'Rack A - Heavy Stock',
    quantity: 50,
    beforeQuantity: 93,
    afterQuantity: 143,
    userId: 'user_mgr_01',
    userName: 'Marcus Sterling',
    notes: 'Initial vendor batch intake from Apex Steel',
    createdAt: '2026-01-15T09:30:00Z',
  },
  {
    id: 'ledg_002',
    productId: 'prod_office_chair',
    productName: 'Ergonomic Office Chair',
    sku: 'FURN-CHR-002',
    operationType: 'DELIVERY',
    referenceId: 'del_001',
    referenceNumber: 'DEL-2026-0001',
    fromWarehouseId: 'wh_main',
    fromWarehouseName: 'Main Warehouse',
    fromLocationId: 'loc_rack_b',
    fromLocationName: 'Rack B - Finished Units',
    quantity: 10,
    beforeQuantity: 30,
    afterQuantity: 20,
    userId: 'user_mgr_01',
    userName: 'Marcus Sterling',
    notes: 'Sales order dispatch to Apex Innovations Corp',
    createdAt: '2026-01-16T13:45:00Z',
  },
  {
    id: 'ledg_003',
    productId: 'prod_office_chair',
    productName: 'Ergonomic Office Chair',
    sku: 'FURN-CHR-002',
    operationType: 'RECEIPT',
    referenceId: 'rec_002',
    referenceNumber: 'REC-2026-0002',
    toWarehouseId: 'wh_main',
    toWarehouseName: 'Main Warehouse',
    toLocationId: 'loc_rack_b',
    toLocationName: 'Rack B - Finished Units',
    quantity: 15,
    beforeQuantity: 20,
    afterQuantity: 35,
    userId: 'user_staff_01',
    userName: 'Devon Miller',
    notes: 'Received shipment from ErgoTech',
    createdAt: '2026-01-18T14:30:00Z',
  },
  {
    id: 'ledg_004',
    productId: 'prod_steel_rod',
    productName: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    operationType: 'TRANSFER',
    referenceId: 'trf_001',
    referenceNumber: 'TRF-2026-0001',
    fromWarehouseId: 'wh_main',
    fromWarehouseName: 'Main Warehouse',
    fromLocationId: 'loc_rack_a',
    fromLocationName: 'Rack A - Heavy Stock',
    toWarehouseId: 'wh_prod',
    toWarehouseName: 'Production Warehouse',
    toLocationId: 'loc_bulk_storage',
    toLocationName: 'Bulk Raw Storage',
    quantity: 50,
    beforeQuantity: 143,
    afterQuantity: 93,
    userId: 'user_staff_01',
    userName: 'Devon Miller',
    notes: 'Transfer from Main WH to Production WH',
    createdAt: '2026-01-19T11:30:00Z',
  },
  {
    id: 'ledg_005',
    productId: 'prod_steel_rod',
    productName: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    operationType: 'ADJUSTMENT_OUT',
    referenceId: 'adj_001',
    referenceNumber: 'ADJ-2026-0001',
    fromWarehouseId: 'wh_main',
    fromWarehouseName: 'Main Warehouse',
    fromLocationId: 'loc_rack_a',
    fromLocationName: 'Rack A - Heavy Stock',
    quantity: 3,
    beforeQuantity: 93,
    afterQuantity: 90,
    userId: 'user_staff_01',
    userName: 'Devon Miller',
    notes: 'Forklift damage adjustment (-3 kg)',
    createdAt: '2026-01-20T16:00:00Z',
  }
];

export const SEED_SETTINGS: CompanySettings = {
  id: 'company_settings',
  companyName: 'StockSense Global Logistics Inc.',
  companyAddress: '100 Enterprise Way, Suite 400, Chicago, IL 60601',
  defaultWarehouseId: 'wh_main',
  defaultCurrency: 'USD',
  timezone: 'America/Chicago',
  lowStockAlertThreshold: 20,
  emailAlertsEnabled: true,
  enableSoundEffects: true,
};

export const SEED_REORDERING_RULES: ReorderingRule[] = [
  {
    id: 'rule_001',
    productId: 'prod_steel_rod',
    productName: 'Steel Rod (10mm x 3m)',
    sku: 'RAW-STL-001',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    minQuantity: 40,
    preferredQuantity: 100,
    unitOfMeasure: 'kg',
    active: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rule_002',
    productId: 'prod_office_chair',
    productName: 'Ergonomic Office Chair',
    sku: 'FURN-CHR-002',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    minQuantity: 15,
    preferredQuantity: 40,
    unitOfMeasure: 'Units',
    active: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rule_003',
    productId: 'prod_monitor',
    productName: '4K UltraHD 27" Monitor',
    sku: 'ELEC-MON-008',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    minQuantity: 10,
    preferredQuantity: 30,
    unitOfMeasure: 'Units',
    active: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rule_004',
    productId: 'prod_keyboard',
    productName: 'Wireless Mechanical Keyboard',
    sku: 'ELEC-KBD-006',
    warehouseId: 'wh_main',
    warehouseName: 'Main Warehouse',
    minQuantity: 20,
    preferredQuantity: 50,
    unitOfMeasure: 'Units',
    active: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rule_005',
    productId: 'prod_helmet',
    productName: 'Hard Hat Safety Helmet',
    sku: 'SAF-HLM-010',
    warehouseId: 'wh_prod',
    warehouseName: 'Production Warehouse',
    minQuantity: 25,
    preferredQuantity: 60,
    unitOfMeasure: 'Units',
    active: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

